import type { Station } from "@shared/types";

export const BUILT_IN_STATIONS: Station[] = [
  { code: "AC", name: "Acton GO", locationName: "Acton GO" },
  { code: "AD", name: "Allandale Waterfront GO", locationName: "Allandale Waterfront GO" },
  { code: "AG", name: "Agincourt GO", locationName: "Agincourt GO" },
  { code: "AJ", name: "Ajax GO", locationName: "Ajax GO" },
  { code: "AL", name: "Aldershot GO", locationName: "Aldershot GO" },
  { code: "AP", name: "Appleby GO", locationName: "Appleby GO" },
  { code: "AU", name: "Aurora GO", locationName: "Aurora GO" },
  { code: "BA", name: "Barrie South GO", locationName: "Barrie South GO" },
  { code: "BD", name: "Bradford GO", locationName: "Bradford GO" },
  { code: "BE", name: "Bramalea GO", locationName: "Bramalea GO" },
  { code: "BL", name: "Bloor GO", locationName: "Bloor GO" },
  { code: "BM", name: "Bloomington GO", locationName: "Bloomington GO" },
  { code: "BO", name: "Bronte GO", locationName: "Bronte GO" },
  { code: "BR", name: "Brampton Innovation District GO", locationName: "Brampton Innovation District GO" },
  { code: "BU", name: "Burlington GO", locationName: "Burlington GO" },
  { code: "CE", name: "Centennial GO", locationName: "Centennial GO" },
  { code: "CF", name: "Confederation GO", locationName: "Confederation GO" },
  { code: "CL", name: "Clarkson GO", locationName: "Clarkson GO" },
  { code: "CO", name: "Cooksville GO", locationName: "Cooksville GO" },
  { code: "DA", name: "Danforth GO", locationName: "Danforth GO" },
  { code: "DI", name: "Dixie GO", locationName: "Dixie GO" },
  { code: "DW", name: "Downsview Park GO", locationName: "Downsview Park GO" },
  { code: "EA", name: "East Gwillimbury GO", locationName: "East Gwillimbury GO" },
  { code: "EG", name: "Eglinton GO", locationName: "Eglinton GO" },
  { code: "ER", name: "Erindale GO", locationName: "Erindale GO" },
  { code: "ET", name: "Etobicoke North GO", locationName: "Etobicoke North GO" },
  { code: "EX", name: "Exhibition GO", locationName: "Exhibition GO" },
  { code: "GE", name: "Georgetown GO", locationName: "Georgetown GO" },
  { code: "GL", name: "Guelph Central GO", locationName: "Guelph Central GO" },
  { code: "GO", name: "Gormley GO", locationName: "Gormley GO" },
  { code: "GU", name: "Guildwood GO", locationName: "Guildwood GO" },
  { code: "HA", name: "Hamilton GO Centre", locationName: "Hamilton GO Centre" },
  { code: "KC", name: "King City GO", locationName: "King City GO" },
  { code: "KE", name: "Kennedy GO", locationName: "Kennedy GO" },
  { code: "KI", name: "Kitchener GO", locationName: "Kitchener GO" },
  { code: "KP", name: "Kipling GO", locationName: "Kipling GO" },
  { code: "LA", name: "Langstaff GO", locationName: "Langstaff GO" },
  { code: "LI", name: "Old Elm GO", locationName: "Old Elm GO" },
  { code: "LO", name: "Long Branch GO", locationName: "Long Branch GO" },
  { code: "LS", name: "Lisgar GO", locationName: "Lisgar GO" },
  { code: "MA", name: "Malton GO", locationName: "Malton GO" },
  { code: "MD", name: "Mount Dennis GO", locationName: "Mount Dennis GO" },
  { code: "ME", name: "Meadowvale GO", locationName: "Meadowvale GO" },
  { code: "MI", name: "Mimico GO", locationName: "Mimico GO" },
  { code: "MJ", name: "Mount Joy GO", locationName: "Mount Joy GO" },
  { code: "MK", name: "Milliken GO", locationName: "Milliken GO" },
  { code: "ML", name: "Milton GO", locationName: "Milton GO" },
  { code: "MO", name: "Mount Pleasant GO", locationName: "Mount Pleasant GO" },
  { code: "MP", name: "Maple GO", locationName: "Maple GO" },
  { code: "MR", name: "Markham GO", locationName: "Markham GO" },
  { code: "NE", name: "Newmarket GO", locationName: "Newmarket GO" },
  { code: "NI", name: "Niagara Falls GO", locationName: "Niagara Falls GO" },
  { code: "OA", name: "Oakville GO", locationName: "Oakville GO" },
  { code: "OL", name: "Old Cummer GO", locationName: "Old Cummer GO" },
  { code: "OR", name: "Oriole GO", locationName: "Oriole GO" },
  { code: "OS", name: "Durham College Oshawa GO", locationName: "Durham College Oshawa GO" },
  { code: "PA", name: "Pearson Airport Terminal 1", locationName: "Pearson Airport Terminal 1" },
  { code: "PIN", name: "Pickering GO", locationName: "Pickering GO" },
  { code: "PO", name: "Port Credit GO", locationName: "Port Credit GO" },
  { code: "RI", name: "Richmond Hill GO", locationName: "Richmond Hill GO" },
  { code: "RO", name: "Rouge Hill GO", locationName: "Rouge Hill GO" },
  { code: "RU", name: "Rutherford GO", locationName: "Rutherford GO" },
  { code: "SC", name: "Scarborough GO", locationName: "Scarborough GO" },
  { code: "SCTH", name: "St. Catharines GO", locationName: "St. Catharines GO" },
  { code: "SR", name: "Streetsville GO", locationName: "Streetsville GO" },
  { code: "ST", name: "Stouffville GO", locationName: "Stouffville GO" },
  { code: "UI", name: "Unionville GO", locationName: "Unionville GO" },
  { code: "UN", name: "Union Station GO", locationName: "Union Station GO" },
  { code: "WE", name: "Weston GO", locationName: "Weston GO" },
  { code: "WH", name: "Whitby GO", locationName: "Whitby GO" },
  { code: "WR", name: "West Harbour GO", locationName: "West Harbour GO" },
];

